export interface PainPoint {
  text: string
  /** Card IDs from teamCards.ts that address this pain point */
  cardIds: string[]
}

export const PAIN_POINTS: Record<string, PainPoint[]> = {
  "Founder's Office": [
    { text: 'Research takes forever',                        cardIds: ['fo4'] },
    { text: 'Too many meetings',                             cardIds: ['fo5'] },
    { text: 'Lack of visibility into delivery',              cardIds: ['fo2'] },
    { text: 'Executive reporting takes time',                cardIds: ['fo1'] },
    { text: 'Need better strategic insights',                cardIds: ['fo4', 'fo2'] },
    { text: 'Decisions depend on scattered information',     cardIds: ['fo2', 'fo1'] },
    { text: 'Hard to track ownership across teams',          cardIds: ['fo1', 'fo2'] },
  ],
  'Business Development': [
    { text: 'Prospect research is repetitive',               cardIds: ['bd1'] },
    { text: 'Pitch decks take too long',                     cardIds: ['bd2'] },
    { text: 'Proposal turnaround is slow',                   cardIds: ['bd5'] },
    { text: 'Leads are poorly qualified',                    cardIds: ['bd1'] },
    { text: 'Follow-ups get missed',                         cardIds: ['bd4'] },
    { text: 'Competitor research takes hours',               cardIds: ['bd6'] },
    { text: "Discovery calls aren't documented properly",    cardIds: ['bd3'] },
    { text: 'Difficult to personalize outreach at scale',    cardIds: ['bd2'] },
  ],
  'Client Servicing - Brands': [
    { text: "Client information lives in people's heads",    cardIds: ['csb3'] },
    { text: 'Meeting notes get lost',                        cardIds: ['csb1'] },
    { text: 'Follow-ups are inconsistent',                   cardIds: ['csb4'] },
    { text: 'Reporting takes too much time',                 cardIds: ['csb2'] },
    { text: 'Escalations come as surprises',                 cardIds: ['csb5'] },
    { text: 'Difficult to track client commitments',         cardIds: ['csb1'] },
    { text: 'Multiple stakeholders create confusion',        cardIds: ['csb4'] },
    { text: 'Renewal preparation is manual',                 cardIds: ['csb6'] },
  ],
  'Client Servicing - Entertainment': [
    { text: 'Talent and client context gets scattered',      cardIds: ['cse5'] },
    { text: 'Last-minute requests create chaos',             cardIds: ['cse5'] },
    { text: 'Follow-ups are inconsistent',                   cardIds: ['cse4'] },
    { text: 'Reporting takes too much time',                 cardIds: ['cse3'] },
    { text: 'Escalations are spotted too late',              cardIds: ['cse3'] },
    { text: 'Deliverables are difficult to track',           cardIds: ['cse4'] },
    { text: 'Multiple stakeholders create confusion',        cardIds: ['cse5'] },
    { text: 'Meeting notes get lost',                        cardIds: ['cse5'] },
  ],
  'Copy & Content': [
    { text: 'Content feels generic',                         cardIds: ['cc3'] },
    { text: 'Localization takes too much effort',            cardIds: ['cc2'] },
    { text: 'Long-form content loses consistency',           cardIds: ['cc3'] },
    { text: 'ORM content is difficult to scale',             cardIds: ['cc2'] },
    { text: 'Multiple content versions are needed',          cardIds: ['cc2'] },
    { text: 'Research slows content creation',               cardIds: ['cc1'] },
    { text: 'Maintaining brand voice is difficult',          cardIds: ['cc3'] },
    { text: 'Clients restrict AI usage',                     cardIds: ['cc1'] },
  ],
  'Design': [
    { text: 'Content demand keeps increasing',               cardIds: ['d3'] },
    { text: 'Too many rerenders',                            cardIds: ['d1'] },
    { text: 'Carousel consistency breaks',                   cardIds: ['d4'] },
    { text: 'Prompting takes multiple attempts',             cardIds: ['d1'] },
    { text: 'Brand consistency is difficult',                cardIds: ['d4'] },
    { text: 'Creative exploration takes time',               cardIds: ['d3'] },
    { text: 'Design handoffs are repetitive',                cardIds: ['d5'] },
    { text: 'Asset repurposing is manual',                   cardIds: ['d2'] },
  ],
  'Digital Media': [
    { text: 'Campaign optimization takes too long',          cardIds: ['dm6'] },
    { text: 'Reporting is repetitive',                       cardIds: ['dm1'] },
    { text: 'Creative performance analysis is manual',       cardIds: ['dm3'] },
    { text: 'Budget allocation decisions are difficult',     cardIds: ['dm6'] },
    { text: 'Audience insights are hard to extract',         cardIds: ['dm2'] },
    { text: 'Too much data to review',                       cardIds: ['dm1'] },
    { text: 'Weekly reports consume time',                   cardIds: ['dm1'] },
    { text: 'Performance trends are missed',                 cardIds: ['dm4'] },
  ],
  'Finance': [
    { text: 'Monthly reporting takes too long',              cardIds: ['fi2'] },
    { text: 'Invoice reviews are repetitive',                cardIds: ['fi6'] },
    { text: 'Budget tracking is manual',                     cardIds: ['fi1'] },
    { text: 'Forecasting requires too much effort',          cardIds: ['fi3'] },
    { text: 'Financial insights are difficult to extract',   cardIds: ['fi1'] },
    { text: 'Data reconciliation is slow',                   cardIds: ['fi6'] },
    { text: 'Vendor management is fragmented',               cardIds: ['fi6'] },
    { text: 'Leadership updates take time',                  cardIds: ['fi5'] },
  ],
  'Influencer Marketing': [
    { text: 'Finding creators takes too long',               cardIds: ['im1'] },
    { text: 'Creator research is manual',                    cardIds: ['im1'] },
    { text: 'Campaign reporting is repetitive',              cardIds: ['im2'] },
    { text: 'Difficult to compare influencers',              cardIds: ['im5'] },
    { text: 'Outreach personalization is slow',              cardIds: ['im4'] },
    { text: 'Performance insights are scattered',            cardIds: ['im2'] },
    { text: 'Trend spotting is difficult',                   cardIds: ['im6'] },
    { text: 'Campaign planning takes too much effort',       cardIds: ['im3'] },
  ],
  'Management': [
    { text: 'Team visibility is limited',                    cardIds: ['mg1'] },
    { text: 'Decisions depend on scattered information',     cardIds: ['mg1'] },
    { text: 'Cross-functional updates take too long',        cardIds: ['mg4'] },
    { text: 'Executive reporting is manual',                 cardIds: ['mg1'] },
    { text: 'Risks are identified too late',                 cardIds: ['mg5'] },
    { text: 'Strategic reviews require excessive preparation',cardIds: ['mg3'] },
    { text: 'Ownership is difficult to track',               cardIds: ['mg3'] },
    { text: 'Too many meetings consume time',                cardIds: ['mg2'] },
  ],
  'Partnerships': [
    { text: 'Partnership research takes too long',           cardIds: ['par1'] },
    { text: 'Outreach personalization is slow',              cardIds: ['par4'] },
    { text: 'Proposal creation is repetitive',               cardIds: ['par2'] },
    { text: 'Follow-ups are inconsistent',                   cardIds: ['par4'] },
    { text: 'Opportunity tracking is fragmented',            cardIds: ['par3'] },
    { text: 'Stakeholder information is scattered',          cardIds: ['par6'] },
    { text: 'Meeting notes get lost',                        cardIds: ['par6'] },
    { text: 'Competitive partnership analysis is manual',    cardIds: ['par5'] },
  ],
  'People & Culture': [
    { text: 'Candidate information gets lost',               cardIds: ['pc1'] },
    { text: 'Hiring updates are scattered',                  cardIds: ['pc1'] },
    { text: 'Recruitment reporting is manual',               cardIds: ['pc5'] },
    { text: 'Employee reminders are inconsistent',           cardIds: ['pc6'] },
    { text: 'Survey analysis takes too long',                cardIds: ['pc3'] },
    { text: 'Milestone tracking is difficult',               cardIds: ['pc5'] },
    { text: 'Internal communication is repetitive',          cardIds: ['pc6'] },
    { text: 'Knowledge is spread across tools',              cardIds: ['pc4'] },
  ],
  'Planning': [
    { text: 'Research takes too long',                       cardIds: ['pl2'] },
    { text: 'Too much information to process',               cardIds: ['pl3'] },
    { text: 'Consumer insights are hard to extract',         cardIds: ['pl3'] },
    { text: 'Building presentations is slow',                cardIds: ['pl4'] },
    { text: 'Trend analysis is manual',                      cardIds: ['pl6'] },
    { text: 'Strategic recommendations take time',           cardIds: ['pl1'] },
    { text: 'Competitive intelligence is scattered',         cardIds: ['pl2'] },
    { text: 'Need stronger campaign insights',               cardIds: ['pl5'] },
  ],
  'SEO': [
    { text: 'Keyword research takes too long',               cardIds: ['seo1'] },
    { text: 'Content briefs are repetitive',                 cardIds: ['seo2'] },
    { text: 'Competitor analysis is manual',                 cardIds: ['seo1'] },
    { text: 'Technical audits are time-consuming',           cardIds: ['seo3'] },
    { text: 'SERP changes are hard to monitor',              cardIds: ['seo5'] },
    { text: 'Content optimization is inconsistent',          cardIds: ['seo2'] },
    { text: 'Opportunity discovery is difficult',            cardIds: ['seo4'] },
    { text: 'Reporting takes too much effort',               cardIds: ['seo5'] },
  ],
  'Strategy': [
    { text: 'Research synthesis is slow',                    cardIds: ['st6'] },
    { text: 'Hard to spot patterns across data',             cardIds: ['st6'] },
    { text: 'Strategy decks take too long',                  cardIds: ['st3'] },
    { text: 'Need better hypothesis generation',             cardIds: ['st5'] },
    { text: 'Long documents are difficult to analyze',       cardIds: ['st6'] },
    { text: 'Market intelligence is fragmented',             cardIds: ['st1'] },
    { text: 'Insight generation feels repetitive',           cardIds: ['st6'] },
    { text: 'Recommendations need stronger evidence',        cardIds: ['st2'] },
  ],
  'Video': [
    { text: 'Too many generations before usable output',     cardIds: ['v1'] },
    { text: 'Production cycles are too long',                cardIds: ['v2'] },
    { text: 'Results are inconsistent',                      cardIds: ['v1'] },
    { text: 'Creative iteration is slow',                    cardIds: ['v5'] },
    { text: 'Difficult to create repeatable workflows',      cardIds: ['v2'] },
    { text: 'Storyboarding is manual',                       cardIds: ['v5'] },
    { text: 'Video ideation takes time',                     cardIds: ['v4'] },
    { text: 'Multiple versions are needed',                  cardIds: ['v6'] },
  ],
  'Video Production': [
    { text: 'Shoot planning takes too long',                 cardIds: ['vp1'] },
    { text: 'Call sheets are created manually',              cardIds: ['vp1'] },
    { text: 'Production documentation is scattered',         cardIds: ['vp1'] },
    { text: 'Client feedback becomes difficult to track',    cardIds: ['vp2'] },
    { text: 'Post-production coordination is slow',          cardIds: ['vp3'] },
    { text: 'Budget tracking is manual',                     cardIds: ['vp1'] },
    { text: 'Asset organization is messy',                   cardIds: ['vp6'] },
    { text: 'Project visibility is limited',                 cardIds: ['vp1'] },
  ],
  'Web & Tech': [
    { text: 'Documentation is outdated',                     cardIds: ['wt3'] },
    { text: 'Requirements gathering is inconsistent',        cardIds: ['wt1'] },
    { text: 'Repetitive development tasks consume time',     cardIds: ['wt2'] },
    { text: 'QA processes are manual',                       cardIds: ['wt4'] },
    { text: 'Bug triaging is slow',                          cardIds: ['wt4'] },
    { text: 'Project visibility is limited',                 cardIds: ['wt5'] },
    { text: 'Technical knowledge is scattered',              cardIds: ['wt3'] },
    { text: 'Handoffs create delays',                        cardIds: ['wt2'] },
  ],
  'Capital Z': [
    { text: 'Trend research takes too long',                 cardIds: ['cz1'] },
    { text: 'Audience insights are difficult to uncover',    cardIds: ['cz5'] },
    { text: 'Community conversations are hard to analyze',   cardIds: ['cz5'] },
    { text: 'Content opportunities are missed',              cardIds: ['cz6'] },
    { text: 'Presentation creation is slow',                 cardIds: ['cz6'] },
    { text: 'Competitive intelligence is fragmented',        cardIds: ['cz1'] },
    { text: 'Campaign recommendations need stronger backing',cardIds: ['cz6'] },
    { text: 'Market shifts are difficult to track',          cardIds: ['cz1'] },
  ],
  'Corporate Communications': [
    { text: 'Leadership communication takes too long',       cardIds: ['corp6'] },
    { text: 'Internal announcements are repetitive',         cardIds: ['corp1'] },
    { text: 'Thought leadership content is difficult to scale', cardIds: ['corp6'] },
    { text: 'Messaging consistency is challenging',          cardIds: ['corp4'] },
    { text: 'PR monitoring is manual',                       cardIds: ['corp2'] },
    { text: 'Reputation tracking is fragmented',             cardIds: ['corp2'] },
    { text: 'Executive summaries take time',                 cardIds: ['corp5'] },
    { text: 'Content approval cycles are slow',              cardIds: ['corp1'] },
  ],
  'Admin & Support': [
    { text: 'Requests come from too many channels',          cardIds: ['as4'] },
    { text: 'Administrative tasks are repetitive',           cardIds: ['as5'] },
    { text: 'Follow-ups are missed',                         cardIds: ['as6'] },
    { text: 'Documentation is difficult to maintain',        cardIds: ['as3'] },
    { text: 'Vendor coordination takes time',                cardIds: ['as1'] },
    { text: 'Approvals are hard to track',                   cardIds: ['as6'] },
    { text: 'Knowledge is scattered',                        cardIds: ['as3'] },
    { text: 'Status updates are manual',                     cardIds: ['as1'] },
  ],
}

/**
 * Convert a set of selected pain-point indices into unique card IDs.
 * De-duplicates automatically so the same card isn't added twice.
 */
export function painPointsToCardIds(team: string, selectedIndices: Set<number>): string[] {
  const pts = PAIN_POINTS[team] ?? []
  const seen = new Set<string>()
  selectedIndices.forEach(idx => {
    pts[idx]?.cardIds.forEach(id => seen.add(id))
  })
  return [...seen]
}
